# Welcome to Jekyll!

# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.

# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Unique Student Symposium 2021 - title
tagline: Unique Student Symposium 2021 - tagline
email: alejandro.hernandez.garcia@umontreal.ca
twitter_username: ai_unique
github_username: uss2021
twitter:
  - username: ai_unique
description: Unique Student Symposium 2021 - description
author: Unique Student Symposium 2021 - author
url: https://uss2021.github.io
logo: /assets/images/logo1.png

# Reading Files
include:
  - _pages

# Collections
collections:
  news:
    output: true
    permalink: /:collection/:path/
  projects:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: "news"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag 
