# Welcome to Jekyll!

# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.

# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Alex Hernandez-Garcia
tagline: Machine learning and computational neuroscience
email: alexhdezgarcia@gmail.com
twitter_username: alexhdezgcia
github_username:  alexhernandezgarcia
twitter:
  - username: alexhdezgcia
description: In November 2020 I defended PhD thesis at the University of Osnabrück. I started my PhD in 2016 with Prof. Peter König, as a fellow of the Marie Sklodowska-Curie ITN NexGenVis. I obtained my B.Sc and M.Sc. at the University Carlos III of Madrid and I have been a visiting PhD student at the University of Cambridge with Dr. Tim Kietzmann and at the Spinoza Center for Neuroimaging with Dr. Serge Dumoulin. My main research focus is on brain-inspired deep learning and computational neuroscience. I believe that machine learning and neuroscience can highly benefit each other and my aim is exploring and exploiting their synergies.
author: Alex Hernandez-Garcia
url: https://alexhernandezgarcia.github.io
logo: /assets/images/logo1.png

# Reading Files
include:
  - _pages
  - _posters

# Collections
collections:
  news:
    output: true
    permalink: /:collection/:path/
  projects:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: "news"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag 
